# Generated by Django 3.1 on 2020-08-25 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.utcnow, editable=False),
        ),
    ]
