default:
  SECRET_KEY: ""
  DATABASE_URL: ""
  ALLOWED_HOSTS: []
  DEBUG: false
  PORT: 0

development:
  SECRET_KEY: "1"
  ALLOWED_HOSTS:
    - localhost
    - 127.0.0.1
  DEBUG: true
  PORT: 8000

heroku:
  ALLOWED_HOSTS:
    - elenamoiseeva.herokuapp.com
  DEBUG: false